name: Package the commits on the alpha, beta or release branches

on:
  push:
    branches:
      - alpha/*
      - beta/*
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the addon
        uses: actions/checkout@v2

      - name: Create the package
        uses: BigWigsMods/packager@master
        with:
          args: -d -z

      - name: Upload the package as artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: SylingTracker-${{ github.sha }}
          path: .release/
